### ISSUE TITLE
Error when I try to make the dance motion of Decided

### ISSUE THREAD

**Issue by TrobridgeWolfCreations** [OpenMLTD/MLTDTools#68]
![MilDanSC](https://user-images.githubusercontent.com/108102479/210290126-be84520c-e712-433c-8759-08025634f4c9.png)

**What assets can I download instead of trying to generate an SSR?**

_In case if you can't read the text on the image, here  is what it says:_

`System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at OpenMLTD.MillionDance.Core.VmdCreator.CreateBoneFrames(IBodyAnimationSource mainDance, PrettyAvatar avatar, PmxModel pmx, ScenarioObject baseScenario, ScenarioObject formationInfo, IBodyAnimationSource danceAppeal, Int32 formationNumber, AppealType appealType) in C:\projects\mltdtools\src\MillionDance\Core\VmdCreator.Dance.cs:line 35
   at OpenMLTD.MillionDance.Core.VmdCreator.CreateDanceMotion(IBodyAnimationSource mainDance, ScenarioObject baseScenario, ScenarioObject formationInfo, PrettyAvatar avatar, PmxModel mltdPmxModel, IBodyAnimationSource danceAppeal, Int32 formationNumber, AppealType appealType) in C:\projects\mltdtools\src\MillionDance\Core\VmdCreator.Dance.cs:line 25
   at OpenMLTD.MillionDance.MainWorker.DoWorkInternal(Object state) in C:\projects\mltdtools\src\MillionDance\MainWorker.cs:line 489
   at OpenMLTD.MillionDance.MainWorker.DoWork(Object state) in C:\projects\mltdtools\src\MillionDance\MainWorker.cs:line 48`

**Comment by TrobridgeWolfCreations** [comment]
I think I see the issue, the Decided PST cards are not available on the game, because it says "Coming Soon", so once they are available, then it might work the next time I try.
